# -*- coding: utf-8 -*-
{
    "name": "Clinic Patient Card",
    "summary": "Patient card on the contact form (dental clinic)",
    "description": "Extends the Contact (res.partner) form with a full patient "
                   "card: basic info, contacts, medical and dental history. "
                   "Built incrementally, phase by phase.",
    "author": "refreshg",
    "website": "https://github.com/refreshg/clinic",
    "category": "Healthcare",
    "version": "19.0.65.0.0",
    "license": "LGPL-3",
    "depends": [
        "base",
        "contacts",
        "base_address_extended",  # res.city + partner.city_id (patient address picker)
        "hr",  # employees for the staff schedule
        "hr_attendance",  # check-in / check-out + worked hours (S2)
        "product",
        "account",
        "mail",
        "calendar",
        "stock",
        "product_expiry",
        "purchase",
        "sale_management",
        "sale_pdf_quote_builder",
    ],
    "data": [
        "security/clinic_groups.xml",
        "security/ir.model.access.csv",
        "security/clinic_schedule_rules.xml",
        "data/ir_sequence.xml",
        "data/clinic_direction_data.xml",
        "data/clinic_cron.xml",
        "data/clinic_stock_data.xml",
        "data/clinic_shop_seed.xml",
        "data/clinic_icd10_seed.xml",
        "data/clinic_complaint_seed.xml",
        "data/clinic_complaint_form_seed.xml",
        "data/clinic_insurers_seed.xml",
        "data/clinic_cities_seed.xml",
        "data/clinic_shift_data.xml",
        "data/clinic_card_type_data.xml",
        "wizard/clinic_payment_wizard_views.xml",
        "wizard/clinic_cancel_wizard_views.xml",
        "wizard/clinic_slot_finder_views.xml",
        "views/clinic_catalog_views.xml",
        "views/clinic_appointment_views.xml",
        "views/clinic_consent_views.xml",
        "views/clinic_icd10_views.xml",
        "views/clinic_med_card_views.xml",
        "views/clinic_planning_views.xml",
        "views/clinic_shop_views.xml",
        "views/clinic_stock_views.xml",
        "views/clinic_purchase_request_views.xml",
        "views/clinic_b4_views.xml",
        "views/clinic_xray_views.xml",
        "views/res_partner_views.xml",
        "views/clinic_schedule_views.xml",
        "report/clinic_treatment_plan_report.xml",
        "report/clinic_prescription_report.xml",
        "report/clinic_med_card_report.xml",
        "views/clinic_treatment_plan_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "clinic_patient_card/static/src/scss/clinic_partner_soft.scss",
            "clinic_patient_card/static/src/clinic_dialog_discard.js",
            "clinic_patient_card/static/src/clinic_arrived_service.js",
            "clinic_patient_card/static/src/clinic_form_buttons.xml",
            "clinic_patient_card/static/src/planning/clinic_planning.scss",
            "clinic_patient_card/static/src/planning/clinic_planning.js",
            "clinic_patient_card/static/src/planning/clinic_planning.xml",
            "clinic_patient_card/static/src/shop/clinic_supply_shop.scss",
            "clinic_patient_card/static/src/shop/clinic_supply_shop.js",
            "clinic_patient_card/static/src/shop/clinic_supply_shop.xml",
            "clinic_patient_card/static/src/patient_dashboard/clinic_patient_dashboard.scss",
            "clinic_patient_card/static/src/patient_dashboard/clinic_patient_dashboard.js",
            "clinic_patient_card/static/src/patient_dashboard/clinic_patient_dashboard.xml",
            "clinic_patient_card/static/src/supplier_portal/clinic_supplier_portal.scss",
            "clinic_patient_card/static/src/supplier_portal/clinic_supplier_portal.js",
            "clinic_patient_card/static/src/supplier_portal/clinic_supplier_portal.xml",
            "clinic_patient_card/static/src/gender_widget/clinic_gender_icons.scss",
            "clinic_patient_card/static/src/gender_widget/clinic_gender_icons.js",
            "clinic_patient_card/static/src/gender_widget/clinic_gender_icons.xml",
            "clinic_patient_card/static/src/live_search/clinic_live_search.js",
            "clinic_patient_card/static/src/patient_status/clinic_patient_status.js",
            "clinic_patient_card/static/src/patient_status/clinic_patient_status.xml",
            "clinic_patient_card/static/src/patient_status/clinic_patient_status.scss",
            "clinic_patient_card/static/src/schedule/clinic_schedule.scss",
            "clinic_patient_card/static/src/schedule/clinic_schedule.js",
            "clinic_patient_card/static/src/schedule/clinic_schedule.xml",
            "clinic_patient_card/static/src/hours/clinic_worked_hours.scss",
            "clinic_patient_card/static/src/hours/clinic_worked_hours.js",
            "clinic_patient_card/static/src/hours/clinic_worked_hours.xml",
            "clinic_patient_card/static/src/tooth_chart/tooth_chart_data.js",
            "clinic_patient_card/static/src/tooth_chart/tooth_chart_overlays.js",
            "clinic_patient_card/static/src/xray_upload/clinic_lightbox.scss",
            "clinic_patient_card/static/src/xray_upload/clinic_lightbox.js",
            "clinic_patient_card/static/src/xray_upload/clinic_lightbox.xml",
            "clinic_patient_card/static/src/xray_upload/clinic_image_upload.js",
            "clinic_patient_card/static/src/xray_upload/clinic_image_upload.xml",
            "clinic_patient_card/static/src/xray_upload/clinic_image_click.js",
            "clinic_patient_card/static/src/xray_upload/clinic_image_click.xml",
            "clinic_patient_card/static/src/xray_upload/clinic_allergy_upload.js",
            "clinic_patient_card/static/src/xray_upload/clinic_allergy_upload.xml",
            "clinic_patient_card/static/src/perio_chart/perio_chart.scss",
            "clinic_patient_card/static/src/perio_chart/perio_chart.js",
            "clinic_patient_card/static/src/perio_chart/perio_chart.xml",
            "clinic_patient_card/static/src/med_card/med_card.scss",
            "clinic_patient_card/static/src/med_card/med_card.js",
            "clinic_patient_card/static/src/med_card/med_card.xml",
            "clinic_patient_card/static/src/tooth_chart/arch_layout.js",
            "clinic_patient_card/static/src/tooth_chart/tooth_chart.js",
            "clinic_patient_card/static/src/tooth_chart/tooth_chart.xml",
            "clinic_patient_card/static/src/tooth_chart/tooth_chart.scss",
            "clinic_patient_card/static/src/slot_finder/clinic_slot_finder_widget.js",
            "clinic_patient_card/static/src/slot_finder/clinic_new_patient_btn.js",
            "clinic_patient_card/static/src/slot_finder/clinic_new_patient_btn.xml",
            "clinic_patient_card/static/src/slot_finder/clinic_slot_finder_widget.xml",
            "clinic_patient_card/static/src/slot_finder/clinic_booking_chooser.js",
            "clinic_patient_card/static/src/slot_finder/clinic_booking_chooser.xml",
            "clinic_patient_card/static/src/stock_dashboard/clinic_stock_dashboard.scss",
            "clinic_patient_card/static/src/stock_dashboard/clinic_stock_dashboard.js",
            "clinic_patient_card/static/src/stock_dashboard/clinic_stock_dashboard.xml",
            "clinic_patient_card/static/src/visit_page/clinic_visit_page.scss",
            "clinic_patient_card/static/src/visit_page/clinic_visit_page.js",
            "clinic_patient_card/static/src/visit_page/clinic_visit_page.xml",
            "clinic_patient_card/static/src/patient_card_page/clinic_patient_card_page.scss",
            "clinic_patient_card/static/src/patient_card_page/clinic_patient_card_page.js",
            "clinic_patient_card/static/src/patient_card_page/clinic_patient_card_page.xml",
        ],
    },
    "installable": True,
    "application": False,
    "post_init_hook": "_post_init_grant_admin",
}
